parameters:
  - name: azureDevOpsPAT
    type: string
  - name: numberOfAgents
    type: number
  - name: azureDevOpsURL
    type: string
  - name: vmName
    type: string

jobs:
- job: CompileDSC
  displayName: 'Compile DSC'
  pool:
    vmImage: 'windows-latest'
  steps:

    - task: PowerShell@2
      displayName: 'Compile SelfHostedAgent.ps1'
      inputs:
        targetType: 'inline'
        script: |
          cd ./dsc
          Install-Module cChoco -Force
          . ./SelfHostedAgent.ps1
          SelfHostedAgent -azureDevOpsPAT ${{ parameters.azureDevOpsPAT }} -numberOfAgents ${{ parameters.numberOfAgents }} -azureDevOpsURL ${{ parameters.azureDevOpsURL }} -vmName ${{ parameters.vmName }}