parameters:
  - name: terraformPath
    type: string
  - name: terraformVersion
    type: string
  - name: azureDevOpsURL
    type: string
  - name: numberOfAgents
  - name: azureDevOpsPAT
    type: string

jobs:
- job: TerraformValidate
  displayName: 'Validate Terraform'
  pool:
    vmImage: 'windows-latest'
  steps:

  - template: ./compile-dsc.yaml
    parameters:
      azureDevOpsURL: ${{ parameters.azureDevOpsURL }}
      numberOfAgents: ${{ parameters.numberOfAgents }}
      azureDevOpsPAT: ${{ parameters.azureDevOpsPAT }}
      
  - template: ./tf-install.yaml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      
  - template: templates/tests/terraform/validate.yaml@templates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}

  - template: templates/tests/terraform/format.yaml@templates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}

  - task: tfsec@1
    displayName: Run TFSec
    inputs:
      dir: ${{ parameters.terraformPath }}
      publishTestResults: true