parameters:
  - name: terraformPath
    type: string
  - name: terraformVersion
    type: string

jobs:
- job: TerraformValidate
  displayName: 'Validate Terraform'
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: PowerShell@2
    displayName: 'Compile MOFS'
    inputs:
      targetType: filePath
      filePath: ./compile-mof.ps1
      
  - template: ./tf-install.yaml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      
  - template: templates/tests/terraform/allTests.yaml@templates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}
