parameters:
  - name: terraformPath
    type: string
  - name: terraformVersion
    type: string

jobs:
- job: TerraformValidate
  displayName: 'Validate Terraform'
  pool:
    vmImage: 'windows-latest'
  steps:

  - template: ./mof.yaml
      
  - template: ./tf-install.yaml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      
  - template: templates/tests/terraform/allTests.yaml@templates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}
