parameters:
  - name: terraformPath
    type: string
  - name: terraformVersion
    type: string

jobs:
- job: TerraformValidate
  displayName: 'Validate Terraform'
  pool:
    vmImage: 'windows-latest'
  steps:

  - task: PowerShell@2
    displayName: 'Compile MOFS'
    inputs:
      targetType: 'inline'
      script: |
        cd ../dsc
        Install-Module cChoco
        . ./SelfHostedAgent.ps1
        SelfHostedAgent -OutputDir ..\dsc -azureDevOpsPAT "fsdfdfdfb" -numberOfAgents 2 -azureDevOpsURL "https://dev.azure.com/hmcts"
        Get-Content ../dsc/SelfHostedAgent.mof | Set-Content -Encoding utf8 "../terraform/SelfHostedAgent.mof"
      
  - template: ./tf-install.yaml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      
  - template: templates/tests/terraform/allTests.yaml@templates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}
