parameters:
  - name: terraformPath
    type: string
  - name: terraformVersion
    type: string

jobs:
- job: TerraformValidate
  displayName: 'Validate Terraform'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
      
  - template: ./tf-install.yaml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      
  - template: templates/tests/terraform/validate.yaml@templates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}

  - template: templates/tests/terraform/format.yaml@templates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}