parameters:
  - name: terraformPath
    type: string
  - name: terraformVersion
    type: string

jobs:
- job: TerraformValidate
  displayName: 'Validate Terraform'
  pool:
    vmImage: 'windows-latest'
  steps:

  - script: |
      cd ../dsc
      Install-Module cChoco
      ../SelfHostedAgent.ps1
      SelfHostedAgent -OutputDir ../terraform -azureDevOpsPAT "fsdfdfdfb" -numberOfAgents 2 -azureDevOpsURL "https://dev.azure.com/hmcts"
    displayName: 'Create MOF'
      
  - template: ./tf-install.yaml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      
  - template: templates/tests/terraform/allTests.yaml@templates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}
