trigger:
  - master

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: vh-azure-devops-agent

  - name: devOpsURL
    value: 'https://dev.azure.com/hmcts'

  - name: azureLocation
    value: 'uk south'

  - name: tfVersion
    value: latest

  - name: workDir
    value: $(Build.SourcesDirectory)/terraform

  - name: tfVersion
    value: 1.1.9

  - name: serviceConnection
    value: DTS-SHAREDSERVICES-STG-Video Hearings

  - name: stateKey
    value: DevOpsAgent/AzureDevOpsAgent.tfstate

############################################
# Terraform CI. ############################
stages:
- stage: CIBuild
  displayName: 'Terraform CI'
  jobs: 
    - template: ado-pipeline/jobs/terraform-validate.yaml
      parameters:
        terraformPath: $(workDir)
        terraformVersion: $(tfVersion)
############################################
# Terraform Plan. ##########################
- stage: Plan
  displayName: 'Terraform Plan'
  dependsOn:
    - CIBuild
  jobs:
  - job: Terraform_Plan
    displayName: 'Terraform Plan'
    steps:
    - template: ado-pipeline/jobs/set-number-agents.yaml
      parameters:
        numberOfAgents: 2
        workingDirectory: $(workDir)

    - template: ado-pipeline/jobs/replace-token.yaml
      parameters:
        myConnection: $(patToken)
        workingDirectory: $(workDir)
        devOpsUrl: $(devOpsURL)

    - template: ado-pipeline/jobs/terraform-prep.yaml
      parameters:
        terraformVersion: $(tfVersion)
        serviceConnection: $(serviceConnection)
        resourceGroup: $(stateResourceGroup)
        location: $(azureLocation)
        storageAccount: $(stateStorageAccount)
        containerName: tfstate
        stateKey: $(stateKey)
        workingDirectory: $(workDir)

    - template: ado-pipeline/jobs/terraform-plan.yaml
      parameters:
        subscription: $(serviceConnection)
        tfVariables: $(workDir)/adoagent.tfvars
        workingDirectory: $(workDir)

############################################
# Manual Validation. #######################
- stage: Wait
  dependsOn:
    - Plan
  jobs:
    - job: WaitForApproval
      displayName: "Wait for approval"
      pool: server
      steps:
        - template: ado-pipeline/steps/wait.yaml

############################################
# Terraform Apply. #########################
- stage: DeployAzureAgent
  displayName: Terraform Apply
  dependsOn: Wait
  jobs:
  - job: Deploy_Terraform
    displayName: Deploy DevOps Agent
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download Terraform Artifacts
        inputs:
          artifact: '$(Build.BuildId)-AzureDevOps-Agent'
          targetPath: '$(Pipeline.Workspace)/$(Build.BuildId)-AzureDevOps-Agent'

      - task: ExtractFiles@1
        displayName: 'Extract Terraform Artifacts'
        inputs:
          archiveFilePatterns: '$(Pipeline.Workspace)/$(Build.BuildId)-AzureDevOps-Agent/$(Build.BuildId)-AzureDevOps-Agent.zip'
          destinationFolder: '$(Pipeline.Workspace)/$(Build.BuildId)-AzureDevOps-Agent'
          cleanDestinationFolder: false
          overwriteExistingFiles: true
     
      - template: ado-pipeline/jobs/terraform-prep.yaml
        parameters:
          terraformVersion: $(tfVersion)
          serviceConnection: $(serviceConnection)
          resourceGroup: $(stateResourceGroup)
          location: $(azureLocation)
          storageAccount: $(stateStorageAccount)
          containerName: tfstate
          stateKey: $(stateKey)
          workingDirectory: '$(Pipeline.Workspace)/$(Build.BuildId)-AzureDevOps-Agent/terraform'

      - template: ado-pipeline/jobs/terraform-apply.yaml
        parameters:
          subscription: $(serviceConnection)
          planLocation: $(Pipeline.Workspace)/$(Build.BuildId)-AzureDevOps-Agent/terraform/$(Build.BuildId)-AzureDevOps-Agent.tfplan
          workingDirectory: '$(Pipeline.Workspace)/$(Build.BuildId)-AzureDevOps-Agent/terraform'