trigger:
  - master
pr:
  - none

#resources:
  # repositories:
  #   - repository: templates
  #     type: github
  #     name: hmcts/azure-devops-templates
  #     ref: refs/heads/master
  #     endpoint: hmcts

parameters:
  - name: Run_Stage
    displayName: Stage to Run
    type: string
    default: 'Deploy_Agent'
    values:
    - Check_Script
    - Deploy_Agent
    - Destroy_Agent

  - name: environment
    displayName: Environment (sandbox default)
    type: string
    default: sandbox # USE upper and lower
    values:
      - sandbox
      - upper
      - lower

variables:
  - group: vh-azure-devops-agent
  - name: TF_VAR_RG_NAME
    value: "vh-devops-agent-rg-${{ parameters.environment }}"
  - name: TF_VAR_KV_NAME
    value: "vhdoagentkv${{ parameters.environment }}"
  - name: TF_VAR_VM_NAME
    value: "vh-devops-agent-vm-${{ parameters.environment }}"
  - name: TF_VAR_NSG_NAME
    value: "vh-devops-vm-nsg-${{ parameters.environment }}"
  - name: TF_VAR_VNET_NAME
    value: "vh-devops-vnet-${{ parameters.environment }}"

stages:
  
  - stage: Deploy_Agent
    condition: eq('${{ parameters.Run_Stage }}', 'Deploy_Agent')
    displayName: Deploy_Agent
    jobs:
      - job: Deploy_Terraform
        displayName: Deploy Terraform
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
              
          - template: pipeline-steps/terraform-prep.yaml
            parameters:
              terraformVersion: $(tfVersion)
              subscription: $(subscription)
              environment: ${{ parameters.environment }}
              resourceGroup: $(resourceGroup)
              location: $(location)
              storageAccount: $(storageAccount)
              containerName: $(containerName)
              stateKey: $(stateKey)-${{ parameters.environment }}.tfstate
              workingDirectory: $(System.DefaultWorkingDirectory)/$(tfDirectory)

          - template: pipeline-steps/terraform-plan.yaml
            parameters:
              subscription: $(subscription)
              environment: ${{ parameters.environment }}
              tfVariables: $(System.DefaultWorkingDirectory)/$(tfDirectory)/$(tfVariables)
              workingDirectory: $(System.DefaultWorkingDirectory)/$(tfDirectory)

          - template: pipeline-steps/terraform-apply.yaml
            parameters:
              subscription: $(subscription)
              environment: ${{ parameters.environment }}
              planLocation: $(System.DefaultWorkingDirectory)/$(tfDirectory)/${{ parameters.environment }}.tfplan
              workingDirectory: $(System.DefaultWorkingDirectory)/$(tfDirectory)

  - stage: Destroy_Agent
    displayName: Destroy_Agent
    condition: eq('${{ parameters.Run_Stage }}', 'Destroy_Agent')
    jobs:
    - job: Destroy_Terraform
      displayName: Destroy Terraform
      pool:
        vmImage: 'ubuntu-latest'
      
        steps:
          - template: pipeline-steps/terraform-prep.yaml
            parameters:
              terraformVersion: $(tfVersion)
              subscription: $(subscription)
              environment: ${{ parameters.environment }}
              resourceGroup: $(resourceGroup)
              location: $(location)
              storageAccount: $(storageAccount)
              containerName: $(containerName)
              stateKey: $(stateKey)-${{ parameters.environment }}.tfstate
              workingDirectory: $(System.DefaultWorkingDirectory)/$(tfDirectory)

          - task: TerraformCLI@0
            displayName: Terraform Destroy
            inputs:
              command: destroy
              workingDirectory: $(System.DefaultWorkingDirectory)/$(tfDirectory)
              environmentServiceName: $(subscription)

  - stage: Check_Script
    displayName: Check_Script
    condition: eq('${{ parameters.Run_Stage }}', 'Check_Script')
    jobs:
    - job: Check_Script_Permissions
      displayName: Check_Script_Permissions
      pool:
        vmImage: 'ubuntu-latest'
      
      steps:
        - template: pipeline-steps/terraform-prep.yaml
          parameters:
            terraformVersion: $(tfVersion)
            subscription: $(subscription)
            environment: ${{ parameters.environment }}
            resourceGroup: $(resourceGroup)
            location: $(location)
            storageAccount: $(storageAccount)
            containerName: $(containerName)
            stateKey: $(stateKey)-${{ parameters.environment }}.tfstate
            workingDirectory: $(System.DefaultWorkingDirectory)/$(tfDirectory)
        
        - task: Bash@3
          displayName: 'Check permissions on agent script'
          inputs:
            targetType: 'inline'
            workingDirectory: $(System.DefaultWorkingDirectory)/$(tfDirectory)
            script: |
              cd $(System.DefaultWorkingDirectory)/$(tfDirectory)
              ls -als