---
java:
  image: 'sdshmctspublic.azurecr.io/hmi/azure-devops-agent:v0.1'
  replicas: 2
  ingressHost: vh-azure-devops-agent.{{ .Values.global.environment }}.platform.hmcts.net
  releaseNameOverride: vh-azure-devops-agent
  aadIdentityName: vh-aad-identity
  secrets: 
    AZP_TOKEN:
        secretRef: vsts-agent-secret
        key: azpToken
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - vsts-agent-secret
  environment:
    AZP_URL: "https://hmctsreform.visualstudio.com/"
    AZP_POOL: "vh-sds"
    AZP_WORK: "_work"

